default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: <%= Rails.application.credentials.dig(:aws, :rds, :user) || 'root' %>
  password: <%= Rails.application.credentials.dig(:aws, :rds, :pw) %>
  host: <%= Rails.application.credentials.dig(:aws, :rds, :host) || 'localhost' %>
  port: 3306
  pool: <%= Rails.application.credentials.dig(:aws, :rds, :pool) || 5 %>

development:
  <<: *default
  database: my-stocks_development

test:
  <<: *default
  database: my-stocks_test

staging:
  <<: *default
  database: my-stocks_staging

production:
  <<: *default
  database: my-stocks_production
