---
name: milestone
on:
  schedule:
    - cron: '50 11 * * *'

jobs:
  create-milestone:
    runs-on: ubuntu-latest
    name: 'create milestone'
    steps:
      - uses: actions/checkout@master
      - name: install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - id: milestone
        name: create milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          due_time=$(date -d"fri 7 days" +"%Y-%m-%dT23:59:59Z")
          title=$(date -d"mon" +"%Y-%m-%d週")
          milestone=`.github/workflows/create-milestone.sh ${{ github.repository }} ${title} ${due_time}`
          sudo echo ::set-output name=milestone_id::$milestone
