name: Create Weekly Milestone
on:
  schedule:
    - cron: '40 14 * * *'

jobs:
  create-weekly-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const date = new Date().toLocaleString({ timeZone: 'Asia/Tokyo' });
            date.setDate(date.getDate() + 7)
            const due_on = date.toISOString()
            const endDate = (date.getMonth() + 1) + "/" + date.getDate()
            github.issues.createMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: " ～ " + endDate,
              due_on: due_on
            })
